fix

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -13,12 +13,20 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v2
-      
+
     - name: get istioctl
       id: get-istioctl
       uses: istio/get-istioctl@main
       with:
         version: '1.22.2'
+    - name: Run Test
+      run: |
+        if [ $(istioctl version --remote=false) == "1.22.2" ]; then
+            echo "Test Passed"
+        else
+            echo "Test Failed"
+            exit 1
+        fi
 
     - name: Install Cosign
       uses: sigstore/cosign-installer@v3.5.0
